name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: CICD ENV
    env:
      DATABASE_HOSTNAME: ${{DATABASE_HOSTNAME}}
      DATABASE_PORT:  ${{DATABASE_PORT}}
      DATABASE_PASSWORD: ${{DATABASE_PASSWORD}}
      DATABASE_NAME: ${{DATABASE_NAME}}
      DATABASE_USERNAME: ${{DATABASE_USERNAME}}
      SECRET_KEY: ${{SECRET_KEY}}
      ALGORITHM: ${{ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ACCESS_TOKEN_EXPIRE_MINUTES}}

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Installing all dependencies
        run: pip install -r requirements.txt

      - name: Running tests (pytest)
        run: |
          pip install pytest
          pytest -v -s
